#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cffi
Version  : 1.15.0
Release  : 116
URL      : https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz
Summary  : Foreign Function Interface for Python calling C code.
Group    : Development/Tools
License  : MIT
Requires: pypi-cffi-license = %{version}-%{release}
Requires: pypi-cffi-python = %{version}-%{release}
Requires: pypi-cffi-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : libffi-dev
BuildRequires : pkgconfig(libffi)
BuildRequires : pypi(pycparser)

%description
CFFI
====
Foreign Function Interface for Python calling C code.
Please see the [Documentation](http://cffi.readthedocs.org/) or uncompiled
in the doc/ subdirectory.

%package license
Summary: license components for the pypi-cffi package.
Group: Default

%description license
license components for the pypi-cffi package.


%package python
Summary: python components for the pypi-cffi package.
Group: Default
Requires: pypi-cffi-python3 = %{version}-%{release}

%description python
python components for the pypi-cffi package.


%package python3
Summary: python3 components for the pypi-cffi package.
Group: Default
Requires: python3-core
Provides: pypi(cffi)
Requires: pypi(pycparser)

%description python3
python3 components for the pypi-cffi package.


%prep
%setup -q -n cffi-1.15.0
cd %{_builddir}/cffi-1.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649725736
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cffi
cp %{_builddir}/cffi-1.15.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cffi/65e8b9015ffb0747c23370a3d3af2a796c64780e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cffi/65e8b9015ffb0747c23370a3d3af2a796c64780e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
